version: '3.3'

volumes:
  postgres-volume:

services:
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"